import type { AgentAdapter, AgentInput, RunContext } from "@ignitionai/core";
import { createDataset } from "@ignitionai/core";
import {
  citationPresence,
  compositeReward,
  containsAll,
  costPenalty,
  latencyPenalty,
} from "@ignitionai/evals";
import { createExperiment } from "@ignitionai/experiments";
import { recommendVariant } from "@ignitionai/trainer";

type StrategyName = "direct-answer" | "rag-basic" | "rag-with-verification";

interface StrategyProfile {
  name: StrategyName;
  latencyMs: number;
  costUsd: number;
  tools: string[];
}

const dataset = createDataset({
  name: "ignitionrag-context-engineering",
  description: "Compares context and workflow strategies with the same mocked base model.",
  items: [
    {
      id: "contract-risk",
      input: "Identify the main risks in this contract.",
      expected: {
        contains: ["termination", "liability", "notice period"],
        citations: ["contract.md#termination", "contract.md#liability"],
      },
    },
    {
      id: "rag-platform",
      input: "Explain what IgnitionRAG does.",
      expected: {
        contains: ["RAG", "agents", "evaluation", "workflows"],
        citations: ["ignitionrag.md#overview"],
      },
    },
    {
      id: "support-policy",
      input: "When should an agent ask for clarification?",
      expected: {
        contains: ["ambiguous", "missing context", "clarification"],
        citations: ["support-policy.md#clarification"],
      },
    },
  ],
});

const strategies: StrategyProfile[] = [
  {
    name: "direct-answer",
    latencyMs: 260,
    costUsd: 0.0006,
    tools: [],
  },
  {
    name: "rag-basic",
    latencyMs: 720,
    costUsd: 0.002,
    tools: ["retrieve_context"],
  },
  {
    name: "rag-with-verification",
    latencyMs: 1250,
    costUsd: 0.004,
    tools: ["retrieve_context", "verify_grounding"],
  },
];

const variants = strategies.map((strategy) => ({
  id: strategy.name,
  name: strategy.name,
  adapter: createStrategyAdapter(strategy),
}));

const result = await createExperiment({
  name: "context-engineering-strategies",
  dataset,
  variants,
  rewards: [
    compositeReward(
      [
        containsAll({ weight: 0.65 }),
        citationPresence({ weight: 0.35 }),
      ],
      { name: "answer_quality", weight: 0.75 },
    ),
    latencyPenalty({ maxLatencyMs: 1500, weight: 0.15 }),
    costPenalty({ maxCostUsd: 0.006, weight: 0.1 }),
  ],
  options: {
    concurrency: 3,
  },
}).run();

printExperimentSummary();

function createStrategyAdapter(strategy: StrategyProfile): AgentAdapter {
  return {
    name: strategy.name,
    run(input: AgentInput, _context: RunContext) {
      return {
        output: answerWithSameBaseModel(input.id, strategy.name),
        trace: {
          steps: [
            {
              type: "message",
              role: "user",
              content: input.input,
            },
            ...strategy.tools.map((tool) => ({
              type: "tool_call" as const,
              name: tool,
              input: { caseId: input.id },
            })),
            {
              type: "message",
              role: "assistant",
              content: `Final answer generated by the same mocked model via ${strategy.name}.`,
            },
          ],
        },
        usage: {
          latencyMs: strategy.latencyMs,
          costUsd: strategy.costUsd,
        },
        metadata: {
          baseModel: "mock-ignition-model",
          strategy: strategy.name,
        },
      };
    },
  };
}

function answerWithSameBaseModel(caseId: string, strategy: StrategyName): string {
  const answers: Record<string, Record<StrategyName, string>> = {
    "contract-risk": {
      "direct-answer": "The contract has termination risk and should be reviewed.",
      "rag-basic":
        "The main contract risks are termination rights and liability exposure. [contract.md#termination]",
      "rag-with-verification":
        "The main risks are broad termination rights, liability exposure and a short notice period. [contract.md#termination] [contract.md#liability]",
    },
    "rag-platform": {
      "direct-answer": "IgnitionRAG helps teams build RAG systems for agents.",
      "rag-basic":
        "IgnitionRAG supports RAG workflows for agents and evaluation of production answers. [ignitionrag.md#overview]",
      "rag-with-verification":
        "IgnitionRAG helps teams run RAG workflows for agents, compare evaluation results and improve production workflows. [ignitionrag.md#overview]",
    },
    "support-policy": {
      "direct-answer": "The agent should ask when the request is unclear.",
      "rag-basic":
        "The agent should ask for clarification when the user request is ambiguous or missing context.",
      "rag-with-verification":
        "The agent should ask for clarification when the request is ambiguous or missing context, before producing a risky answer. [support-policy.md#clarification]",
    },
  };

  const answer = answers[caseId]?.[strategy];
  if (answer === undefined) throw new Error(`No mocked answer for ${caseId} using ${strategy}.`);
  return answer;
}

function printExperimentSummary(): void {
  const recommendation = recommendVariant(result);

  console.log(`Experiment: ${result.name}`);
  console.log(`Dataset items: ${dataset.items.length}`);
  console.log(`Variants: ${variants.map((variant) => variant.name).join(", ")}`);
  console.log("");
  console.log("Leaderboard:");
  result.leaderboard.forEach((row, index) => {
    console.log(`${index + 1}. ${row.name} - ${row.score.toFixed(2)}`);
  });
  console.log("");
  console.log("Recommendation:");
  if (recommendation === null) {
    console.log("No recommendation is available for an empty leaderboard.");
    return;
  }

  console.log(recommendation.summary);
  console.log("Reasons:");
  for (const reason of recommendation.reasons) {
    console.log(`- ${reason}`);
  }
  console.log("Tradeoffs:");
  for (const tradeoff of recommendation.tradeoffs) {
    console.log(`- ${tradeoff}`);
  }
  console.log(`Confidence: ${recommendation.confidence}`);
}
